### ISSUE TITLE
Vector math problem

### ISSUE THREAD

**Issue by Alex-146** [dbrizov/NaughtyCharacter#4]
I want to say thanks for `DrawGizmoSphere` function in `SpringArm.cs`. I am using it in external resources for drawing wire sphere, since there is no quaternions there, I just swapped `y` and `z` coords inside `GetSphericalPoint` function and it works great.
I want to draw a circle shape around given normal, by default my points are in XZ plane and I want to achive flexible way to position it (same as https://docs.unity3d.com/ScriptReference/Handles.DrawWireDisc.html)
```csharp
// here is my unity code but same calculations applied in javascript
Vector3[] positions = new Vector3[Count];
float stepSize = 360f / Count;
for (int i = 0; i < positions.Length; i++)
{
    float angle = i * stepSize * Mathf.Deg2Rad;
    positions[i].x = Mathf.Sin(angle) * Radius;
    positions[i].z = Mathf.Cos(angle) * Radius;
}
```
It would be great if you can help me :smile:

Here is some screenshots (manually changed coords)

Normal - `Vector3.up`
![vector normal up](https://user-images.githubusercontent.com/82390349/132354702-129b6fbc-eefd-4d1b-9ba7-446e3d4171eb.png)

Normal - `Vector3.forward`
![vector normal forward](https://user-images.githubusercontent.com/82390349/132354831-3633b287-74f2-4e46-9029-9a748b3b16a6.png)

Normal - `Vector3.right`
![vector normal right](https://user-images.githubusercontent.com/82390349/132354844-f7b51d1a-8a71-41a5-97be-def5466a50ab.png)

**Comment by dbrizov** [comment]
Hi,

Sorry for the late reply. You can use Quaternions to do that.
Quaterions have a really nice feature that they can rotate points by using
the * operator

public int Count = 12;
public float Radius = 1.0f;
public Vector3 Normal = Vector3.up;

private void OnDrawGizmos()
{
    Vector3[] positions = new Vector3[Count];

    float stepSize = 360f / Count;

    // Generate points on the XZ axis
    for (int i = 0; i < positions.Length; i++)
    {
        float angle = i * stepSize * Mathf.Deg2Rad;
        positions[i].x = Mathf.Sin(angle) * Radius;
        positions[i].z = Mathf.Cos(angle) * Radius;
    }

    // Rotate the points from the reference up direction to the direction
of the provided normal
    Quaternion rotation = Quaternion.FromToRotation(Vector3.up, Normal);
    foreach (var point in positions)
    {
        Gizmos.DrawSphere(rotation * point, 0.1f);
    }
}

**Comment by Alex-146** [comment]
Yeah, I solved this task in unity by using `Quaternion.FromToRotation` recently, but now I am trying to do this in another environment where there is no quaternion calculations (vanilla javascript, maybe I should dig into external library like `three.js`).
Any thoughts how to solve using `cross` and `dot` products?
