### ISSUE TITLE
Where is the code from character collisions ?

### ISSUE THREAD

**Issue by horemhamer** [dbrizov/NaughtyCharacter#6]
I would like to know where the collisions are programmed since I have added an animation of crouching to the character and they work badly for me.

**Comment by dbrizov** [comment]
The collisions are handled by Unity's CharacterController. It uses an
algorithm called "collide and slide". You basically have to override the
collision check functions associated with the CharacterController

**Comment by horemhamer** [comment]
I've never really used that, I've always used box colliders, etc.

**Comment by dbrizov** [comment]
When you make a call to the Move() function of the CharacterController, it
handles collisions automatically. Internally they are using NVIDIAs API for
character controllers. There is the actual collide and slide algorithm
implementation

**Comment by horemhamer** [comment]
If anything about how it works can happen to me, because I honestly don't know how to do it

**Comment by horemhamer** [comment]
I haven't been using unity for a long time

**Comment by horemhamer** [comment]
I have been able to solve it, I don't know if you mean this xd, I have modified the parameters of the character controller
